name: Publish Extension

on:
  push:
    tags:
      - 'v*'  # Triggers on tags like v1.0.0

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'

    - name: Install Dependencies
      run: npm install

    - name: Package Extension
      run: npx @vscode/vsce package

    - name: Publish to VS Code Marketplace
      run: npx @vscode/vsce publish -p ${{ secrets.VSCE_TOKEN }}

    - name: Publish to Open VSX
      run: npx ovsx publish -p ${{ secrets.OVSX_TOKEN }}
         
    - name: Create GitHub Release
      uses: softprops/action-gh-release@v1
      with:
        files: '*.vsix'
      env:
        GITHUB_TOKEN: ${{ secrets.GH_RELEASE_TOKEN }}